Package.describe({
  name: 'heaven7:date',
  version: '0.0.2',
  summary: 'Date package with template helper',
  git: 'https://github.com/heaven7/date.git',
  documentation: 'README.md'
})

var both = ['client','server'],
    packages = [
        'copleykj:livestamp@1.1.7',
        'momentjs:moment@2.13.1',
        'rzymek:moment-locale-af@2.12.0',
        'rzymek:moment-locale-ar@2.12.0',
        'rzymek:moment-locale-ar-ma@2.12.0',
        'rzymek:moment-locale-ar-sa@2.12.0',
        'rzymek:moment-locale-az@2.12.0',
        'rzymek:moment-locale-be@2.12.0',
        'rzymek:moment-locale-bg@2.12.0',
        'rzymek:moment-locale-bn@2.12.0',
        'rzymek:moment-locale-bo@2.9.0',
        'rzymek:moment-locale-br@2.12.0',
        'rzymek:moment-locale-bs@2.12.0',
        'rzymek:moment-locale-ca@2.12.0',
        'rzymek:moment-locale-cs@2.12.0',
        'rzymek:moment-locale-cv@2.12.0',
        'rzymek:moment-locale-cy@2.12.0',
        'rzymek:moment-locale-da@2.12.0',
        'rzymek:moment-locale-de@2.12.0',
        'rzymek:moment-locale-de-at@2.12.0',
        'rzymek:moment-locale-el@2.12.0',
        'rzymek:moment-locale-en-au@2.12.0',
        'rzymek:moment-locale-en-ca@2.12.0',
        'rzymek:moment-locale-en-gb@2.12.0',
        'rzymek:moment-locale-eo@2.12.0',
        'rzymek:moment-locale-et@2.12.0',
        'rzymek:moment-locale-eu@2.12.0',
        'rzymek:moment-locale-es@2.12.0',
        'rzymek:moment-locale-fa@2.12.0',
        'rzymek:moment-locale-fi@2.12.0',
        'rzymek:moment-locale-fo@2.12.0',
        'rzymek:moment-locale-fr@2.12.0',
        'rzymek:moment-locale-fr-ca@2.12.0',
        'rzymek:moment-locale-gl@2.12.0',
        'rzymek:moment-locale-he@2.12.0',
        'rzymek:moment-locale-hi@2.12.0',
        'rzymek:moment-locale-hr@2.12.0',
        'rzymek:moment-locale-hu@2.12.0',
        'rzymek:moment-locale-hy-am@2.12.0',
        'rzymek:moment-locale-id@2.12.0',
        'rzymek:moment-locale-is@2.12.0',
        'rzymek:moment-locale-it@2.12.0',
        'rzymek:moment-locale-ja@2.12.0',
        'rzymek:moment-locale-ka@2.12.0',
        'rzymek:moment-locale-km@2.12.0',
        'rzymek:moment-locale-ko@2.12.0',
        'rzymek:moment-locale-lb@2.12.0',
        'rzymek:moment-locale-lt@2.12.0',
        'rzymek:moment-locale-lv@2.12.0',
        'rzymek:moment-locale-mk@2.12.0',
        'rzymek:moment-locale-ml@2.12.0',
        'rzymek:moment-locale-mr@2.12.0',
        'rzymek:moment-locale-ms-my@2.12.0',
        'rzymek:moment-locale-my@2.12.0',
        'rzymek:moment-locale-nb@2.12.0',
        'rzymek:moment-locale-ne@2.12.0',
        'rzymek:moment-locale-nl@2.12.0',
        'rzymek:moment-locale-nn@2.12.0',
        'rzymek:moment-locale-pl@2.12.0',
        'rzymek:moment-locale-pt@2.12.0',
        'rzymek:moment-locale-pt-br@2.12.0',
        'rzymek:moment-locale-ro@2.12.0',
        'rzymek:moment-locale-ru@2.12.0',
        'rzymek:moment-locale-sk@2.12.0',
        'rzymek:moment-locale-sl@2.12.0',
        'rzymek:moment-locale-sq@2.12.0',
        'rzymek:moment-locale-sr@2.12.0',
        'rzymek:moment-locale-sr-cyrl@2.12.0',
        'rzymek:moment-locale-sv@2.12.0',
        'rzymek:moment-locale-ta@2.12.0',
        'rzymek:moment-locale-th@2.12.0',
        'rzymek:moment-locale-tl-ph@2.12.0',
        'rzymek:moment-locale-tr@2.12.0',
        'rzymek:moment-locale-tzm@2.12.0',
        'rzymek:moment-locale-tzm-latn@2.12.0',
        'rzymek:moment-locale-uk@2.12.0',
        'rzymek:moment-locale-uz@2.12.0',
        'rzymek:moment-locale-vi@2.12.0',
        'rzymek:moment-locale-zh-cn@2.12.0',
        'rzymek:moment-locale-zh-tw@2.12.0',
        'templating',
        'tracker',
        'reactive-var',
        'es5-shim',
        'ecmascript',
        'jquery'
]

Package.onUse(function(api) {
    api.versionsFrom('1.2')
    api.use(packages, both)
    api.imply(packages)

    api.addFiles([
        'lib/client/api.js',
        'lib/client/locale.js',
        'lib/client/helpers.js',
        'lib/client/mdate.js'
    ], 'client')

    api.export(['mDate'], 'client')
})
